<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Exe</OutputType>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="WixSharp" Version="1.*" />
        <PackageReference Include="WixSharp.wix.bin" Version="3.*" />
    </ItemGroup>

</Project>
